import QueryClientProviders from "@/hooks/providers/queryClientProviders";
import "@/styles/variable.scss";
import "@/styles/globals.scss";

export const metadata = {
  title: "Kyoung2 MiniGame Web",
  description: "Generated by create next app",
};
const style = {
  margin: "0px",
  width: "100vw",
  height: "100vh",
  background: "var(--color-dark-beige)",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={style}>
        <QueryClientProviders>{children}</QueryClientProviders>
      </body>
    </html>
  );
}
